//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string btnInfo {
            get {
                return ResourceManager.GetString("btnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string btnLanguage {
            get {
                return ResourceManager.GetString("btnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvenstvo:.
        /// </summary>
        public static string Championship {
            get {
                return ResourceManager.GetString("Championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        public static string lblCaptain {
            get {
                return ResourceManager.GetString("lblCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA:.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlučenih:.
        /// </summary>
        public static string lblDraws {
            get {
                return ResourceManager.GetString("lblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih:.
        /// </summary>
        public static string lblGamesPlayed {
            get {
                return ResourceManager.GetString("lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika:.
        /// </summary>
        public static string lblGoalDifferential {
            get {
                return ResourceManager.GetString("lblGoalDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golova primljenih:.
        /// </summary>
        public static string lblGoalsAgainsts {
            get {
                return ResourceManager.GetString("lblGoalsAgainsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golova zabijenih:.
        /// </summary>
        public static string lblGoalsFor {
            get {
                return ResourceManager.GetString("lblGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poraza:.
        /// </summary>
        public static string lblLosses {
            get {
                return ResourceManager.GetString("lblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni golovi:.
        /// </summary>
        public static string lblScoredGoals {
            get {
                return ResourceManager.GetString("lblScoredGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dresa:.
        /// </summary>
        public static string lblShirtNumber {
            get {
                return ResourceManager.GetString("lblShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjeda:.
        /// </summary>
        public static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuti kartoni:.
        /// </summary>
        public static string lblYellowCards {
            get {
                return ResourceManager.GetString("lblYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string rbCroatianLanguage {
            get {
                return ResourceManager.GetString("rbCroatianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string rbEnglishLanguage {
            get {
                return ResourceManager.GetString("rbEnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        public static string rbFemale {
            get {
                return ResourceManager.GetString("rbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        public static string rbMale {
            get {
                return ResourceManager.GetString("rbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string WindowSettings {
            get {
                return ResourceManager.GetString("WindowSettings", resourceCulture);
            }
        }
    }
}
